### ISSUE TITLE
Requires requests package

### ISSUE THREAD

**Issue by dbussert** [lennisthemenace/ATAK-Certs#22]
Following along the instructions, I found `requests` is required. Might just want to put that in Step 2

```[user@localhost tak]$ curl -L https://git.io/JL9DP | sudo python3 -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 23135  100 23135    0     0  72751      0 --:--:-- --:--:-- --:--:-- 72751
Traceback (most recent call last):
  File "<stdin>", line 26, in <module>
ModuleNotFoundError: No module named 'requests'
```

**Comment by lennisthemenace** [comment]
what is actually giving you this error? as the script should be installing it for you

**Comment by dbussert** [comment]
Ran Step 2 `sudo python3 -m pip install pyopenssl`, then on Step 3 the script fails with `ModuleNotFoundError: No module named 'requests'`

**Comment by lennisthemenace** [comment]
so the script is capturing a import error on the import of requests and if it errors it should be installing. but maybe an issue with your exact version you are running. trying just manually installing requests like you do with pyopenssl

**Comment by dbussert** [comment]
that's what i did, just ran `sudo python3 -m pip install pyopenssl requests` instead. I didn't know python scripts would auto-install packages. At least in this (older) version, it doesn't appear to work. Just wanted to pass along.
