### ISSUE TITLE
Interactive mode fails

### ISSUE THREAD

**Issue by dbussert** [lennisthemenace/ATAK-Certs#23]
Running on CentOS 7, default Python 3.6.8. Understandable if you don't want to support a version that old, but might be useful to state what the min version supported is

```
[root@localhost tak]$ curl -L https://git.io/JL9DP | sudo python3 -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 23135  100 23135    0     0  80891      0 --:--:-- --:--:-- --:--:-- 80891
Cannot find CA locally so generating one
CA key Stored Here: ./ca.key
CA pem Stored Here: ./ca.pem
Would you like to generate a server certificate? y/n Traceback (most recent call last):
  File "<stdin>", line 484, in <module>
EOFError: EOF when reading a line
```

**Comment by lennisthemenace** [comment]
did you not get a chance to input your answer before it crashed?

**Comment by lennisthemenace** [comment]
I would try splitting the command out and see if it happens again. 
so run:
curl -L -o cert.py https://git.io/JL9DP
then:
sudo python3 ./cert.py

**Comment by dbussert** [comment]
Running `curl -L https://git.io/JL9DP | sudo python3 -` does wait for an answer before crashing. Splitting works fine.

**Comment by lennisthemenace** [comment]
ok. i will put in a note to split the commends with centos.

**Comment by lennisthemenace** [comment]
updated the readme to reflect this
