### ISSUE TITLE
Creating flags to directly import certificates to FTS folder.

### ISSUE THREAD

**Issue by fieldmapper** [lennisthemenace/ATAK-Certs#6]
One "nice to have" would be a flag where the script automatically copies the certs to the FTS `{userpath}{python_version}/dist-packages/FreeTAKServer/Certs/`, with filenames identical to the ones indicated on tsame configuration file... `pubserver.key`, `pubserver.pem`, `pubserver.key.unencrypted` and `ca.pem`. So end-users won't have to dabble much on the MainConfig.py that much.

Yes, the script will run as root.

**Comment by lennisthemenace** [comment]
added in 0.3.2
